version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    ports:
      - "8002:8001"
    networks:
      - app-network
    depends_on:
      - redis
    restart: unless-stopped
networks:
  app-network:
    driver: bridge
