
spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/prod_db
    username: prod_user
    password: prod_password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

  cache:
    type: redis
    host: host.docker.internal
    port: 6379


springdoc:
  api-docs:
    enabled: true
    path: /v1/api-docs
  swagger-ui:
    defaultModelsExpandDepth: -1
    defaultModelExpandDepth: 0
    displayOperationId: true


logging:
  level:
    org.springframework: DEBUG
