server:
  port: 8081

spring:
  application:
    name: Document-management
  profiles:
    active: dev
  datasource:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: admin
      driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    ddl-auto: update
    open-in-view: false
  cache:
    type: redis
    host: localhost
    port: 6379

springdoc:
  api-docs:
    enabled: true
    path: /v1/api-docs
  swagger-ui:
    defaultModelsExpandDepth: -1
    defaultModelExpandDepth: 0
    displayOperationId: true


logging:
  level.org:
  springframework: DEBUG