
spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/prod_db
    username: prod_user
    password: prod_password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update


  cache:
    type: redis
    host: localhost
    port: 6379


#logging:
#  level:
#    org.springframework: DEBUG
