server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prod_db
    username: prod_user
    password: prod_password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework: DEBUG
